services:
  app:
    image: usermanagerdemo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment: # <<< THÊM PHẦN NÀY
      ASPNETCORE_URLS: "http://+:80" # Yêu cầu ứng dụng lắng nghe trên tất cả các địa chỉ IP trên cổng 80
    volumes:
      # <--- ĐÂY LÀ ĐIỂM QUAN TRỌNG NHẤT ĐỂ HOT-RELOAD HOẠT ĐỘNG
      # Gắn thư mục hiện tại của máy host (nơi chứa docker-compose.yml và mã nguồn)
      # vào thư mục /app bên trong container.
      - .:/app
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

